// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using a2bapi.Data;

#nullable disable

namespace a2bapi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260225213332_SavedHotels")]
    partial class SavedHotels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("a2bapi.Models.SavedFlight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArrivalIata")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("arrival_iata");

                    b.Property<string>("ArrivalTime")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("arrival_time");

                    b.Property<string>("DepartureIata")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("departure_iata");

                    b.Property<string>("DepartureTime")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("departure_time");

                    b.Property<string>("FlightDate")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("flight_date");

                    b.Property<string>("FlightName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("flight_name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SavedFlights");
                });

            modelBuilder.Entity("a2bapi.Models.SavedHotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HotelCountryCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("country_code");

                    b.Property<decimal>("HotelDistance")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("hotel_distance");

                    b.Property<string>("HotelIataCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("iata_code");

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("hotel_name");

                    b.Property<int>("HotelRating")
                        .HasColumnType("int")
                        .HasColumnName("hotel_rating");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SavedHotels");
                });

            modelBuilder.Entity("a2bapi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("a2bapi.Models.SavedFlight", b =>
                {
                    b.HasOne("a2bapi.Models.User", "User")
                        .WithMany("SavedFlights")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("a2bapi.Models.SavedHotel", b =>
                {
                    b.HasOne("a2bapi.Models.User", "User")
                        .WithMany("SavedHotels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("a2bapi.Models.User", b =>
                {
                    b.Navigation("SavedFlights");

                    b.Navigation("SavedHotels");
                });
#pragma warning restore 612, 618
        }
    }
}
